version: '2'
services:
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - "8088:80"
  backend:
    build: .
    ports:
      - "8081:80"
    volumes:
     - ./html:/var/www/html
