version: '2'
services:
  remix:
    image: dltdojo/remix:70f02ab
    ports:
      - "8080:8080"
    volumes:
      - ./mount:/opt/build/browser-solidity/mount
  gethdev:
    image: dltdojo/ethnode:6.a.2
    command: "bash -c \"/opt/geth/start-debug.sh &\
        sleep 5 && \
        echo blocktime 10 secs && \
        /opt/geth/testrpc3.sh 10\""
    ports:
      - "8545:8545"
    volumes:
      - ./nmount:/opt/ddj/nmount
  testrpc:
    image: dltdojo/ethnode:6.a.2
    command: testrpc
    ports:
      - "18545:8545"
  bitcoind:
    image: dltdojo/abe
    command: /testapp.sh
    ports:
      - "12750:12750"