version: '2'
services:
  remix:
    image: dltdojo/remix:70f02ab
    ports:
      - "8080:8080"
  gethdev:
    image: dltdojo/ethnode:6.a.2
    command: /opt/geth/testrpc.sh
    ports:
      - "8545:8545"    
  carexp:
    image: dltdojo/carexp
    ports:
        - "8000:8000"
    command: '/start.sh 192.168.2.103'